name: sportlivetv
description: SportLiveTV - Live sports schedules, scores, stats and premium streaming app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.6
  firebase_messaging: ^14.7.15
  cloud_functions: ^4.6.4
  provider: ^6.1.2
  google_fonts: ^6.2.1
  lottie: ^3.1.0
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  video_player: ^2.8.6
  chewie: ^1.7.5
  youtube_player_flutter: ^9.1.1
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.1
  flutter_local_notifications: ^17.0.0
  url_launcher: ^6.2.5
  uuid: ^4.3.3
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/lottie/
    - assets/lang/
